# ======================
# SHELL
# ======================

shell fish

confirm_os_window_close 0


# ======================
# TRANSPARENCY
# ======================

background_opacity 0.6
dynamic_background_opacity yes


# ======================
# FONT
# ======================

font_family JetBrainsMono Nerd Font
bold_font auto
italic_font auto

font_size 11.5


# ======================
# COLORS
# ======================

foreground #e6e0ff
background #100b18

selection_foreground #100b18
selection_background #b794f6


# ======================
# CURSOR
# ======================

cursor #b794f6
cursor_text_color #100b18

cursor_shape beam
cursor_beam_thickness 2

cursor_blink_interval 0.6
cursor_stop_blinking_after 0


# ======================
# PALETTE
# ======================

# black
color0  #171221
color8  #4b405f

# red
color1  #ff6b9d
color9  #ff85b1

# green
color2  #a6e3a1
color10 #b9f6b5

# yellow
color3  #f9e2af
color11 #ffe9a8

# blue
color4  #82aaff
color12 #9bbcff

# purple
color5  #bd93f9
color13 #d6b3ff

# cyan
color6  #89ddff
color14 #a8e7ff

# white
color7  #cdd6f4
color15 #f5f0ff


# ======================
# WINDOW
# ======================

window_padding_width 10

draw_minimal_borders yes


# ======================
# SCROLL
# ======================

scrollback_lines 10000


# ======================
# BEHAVIOR
# ======================

enable_audio_bell no
visual_bell_duration 0

repaint_delay 10
input_delay 3


# ======================
# CURSOR ANIMATION
# ======================

cursor_trail 10
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 0
