animations {

    enabled = true

    bezier = smooth,0.05,0.9,0.1,1.0

    animation = windows,1,5,smooth
    animation = windowsOut,1,5,smooth,popin 80%
    animation = border,1,6,smooth
    animation = fade,1,5,smooth
    animation = workspaces,1,6,smooth
}
