preload = /home/danil/sddm-astronaut-theme_1781292745/Backgrounds/japanese_aesthetic.png

wallpaper {
    monitor = HDMI-A-1
    path = /home/danil/sddm-astronaut-theme_1781292745/Backgrounds/japanese_aesthetic.png
    fit_mode = cover
}

splash = false
