windowrule {

    name = float pavucontrol

    match:class = pavucontrol

    float = true
}


windowrule {

    name = float blueman

    match:class = blueman-manager

    float = true
}


windowrule {

    name = float network manager

    match:class = nm-connection-editor

    float = true
}


windowrule {

    name = center pavucontrol

    match:class = pavucontrol

    center = true
}


windowrule {

    name = center blueman

    match:class = blueman-manager

    center = true
}
