# ======================
# VARIABLES
# ======================

$mainMod = SUPER

$terminal = kitty
$browser = firefox
$filemanager = dolphin
$launcher = wofi --show drun


# ======================
# LOAD CONFIGS
# ======================

source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/autostart.conf
source = ~/.config/hypr/env.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/appearance.conf
source = ~/.config/hypr/animations.conf
source = ~/.config/hypr/layout.conf
source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/rules.conf
